import { Inter, Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";

import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";

const lato = Lato({ subsets: ["latin"], weight: ['100', '300', '400', '700', '900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }

  return (
    <html lang="en">
      <body className={lato.className}>
        <Toaster/>
        <main className="flex min-h-screen">
          <aside className="bg-white w-48 p-4 shadow">
            <div className="">
              <Image
                className="rounded-full overflow-hidden aspect-square w-24 mx-auto"
                src={session?.user?.image}
                width={128}
                height={128}
                alt="userAvatar"
              />
            </div>
            <div className="text-center">
              <AppSidebar/>
            </div>
          </aside>

          <div className="grow">
            <div className="bg-white m-6 p-4 shadow">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
